#!/bin/bash

echo "File name:"
read filename

echo "Permissions to asign(numeric/octal):"
read permissions

echo "Your file first line"
read bang

# Inserting bang on first line
echo $bang > $filename

# Assingning permissions.
chmod $permissions $filename

# Opening file on editor.
vim $filename
