#!/bin/bash

echo "File name:"
read filename

echo "Permissions to assign, <RETURN> for default (764):"
read permissions

echo "Your file first line, <RETURN> for default (#!/bin/bash)"
read bang

# Inserting bang on first line
if [ $bang = "" ];
  then
    echo $bang > $filename
  else
    echo "#!/bin/bash" > $filename
fi

# Assingning permissions.
if [ $bang = "" ];
  then
    chmod $permissions $filename
  else
    chmod 764 $filename
fi

# Opening file on editor.
vim $filename
